spring:
  application:
    name: twmp-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
           - classpath:/email-service/
           - classpath:/twmp-authorize/
           - classpath:/twmp-gateway/
           - classpath:/twmp-tmp/
           - classpath:/twmp-zipkin/
           - classpath:/twmp-zuul/
           - classpath:/twmp-gps/
server:
  port: 2001
eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:1000/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4